name: Cypress Tests

on:
  workflow_dispatch:
  
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node18.15.0-chrome111.0.5563.146-ff-111.0.1-edge-111.0.1661.62-1
      options: --user 1001
    steps: 
      - name: Get code
        uses: actions/checkout@v3.5.2
        
      - name: Install Dependencies
        run: yarn install
        
      - name: Run E2E Tests
        run: npx cypress run
          
      
    
